name: Dashboard RPM Relase
on:
  push:
    branches:
      - master
jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos7
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'master'
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Package
        run: bash ./scripts/package.sh
      - name: Upload oss
        run: cd tmp/ && ossutil64 -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ID }} -k ${{ secrets.OSS_SECRET }} -f cp ./  ${{ secrets.OSS_URL }} --include "nebula-dashboard-*.rpm*" --only-current-dir -r

    
